language: node_js
services: mongodb
node_js:
  - "10.15.1"
install:
  - npm i
script:
  - export NODE_ENV="MOCHA"
  - npm run lint
  - npm run test
after_script:
  - npm run cover
before_script:
  - cp config/staticConfig.sample.js config/staticConfig.js
  
