language: node_js
node_js:
  - "7.10"
install:
  - npm i
script:
  - npm run lint
  - npm run cover
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage && rm -rf ./.nyc_output
services:
  - mongodb