language: node_js
node_js:
  - "8.15"
install:
  - npm i
script:
  - export NODE_ENV="MOCHA"
  - npm run lint
  - npm run test
after_script:
  - npm run cover
before_script:
  - sudo apt-get purge mongodb-org*
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  - echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  - sudo apt-get update
  - sudo apt-get install --allow-unauthenticated -y mongodb-org
  - sleep 5
  - mongo --version
  - cp config/staticConfig.sample.js config/staticConfig.js
  
