language: node_js
node_js:
  - "7.10"
install:
  - npm i
script:
  - npm run lint
after_script:
  - nyc ./node_modules/mocha/bin/_mocha ./test/ --recursive --timeout 999999 --compilers js:babel-core/register --require babel-polyfill && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage && rm -rf ./.nyc_output
services:
  - mongodb